kind: Deployment
apiVersion: apps/v1
metadata:
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: airflow
  template:
    metadata:
      labels:
        deploy: airflow
    spec:
      containers:

        # AIRFLOW SCHEDULER
      - name: airflow-scheduler
        image: apache/airflow:2.5.0 
        env:
          - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
            value: "postgresql://airflow:airflow@postgres:5432/airflow"
          - name: AIRFLOW__CORE__EXECUTOR
            value: LocalExecutor
        command: ["airflow"]
        args: ["scheduler"]
        
        # AIRFLOW WEBSERVER
      - name: airflow-webserver
        image: apache/airflow:2.5.0
        env:
          - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
            value: "postgresql://airflow:airflow@postgres:5432/airflow"
          - name: AIRFLOW__CORE__EXECUTOR
            value: LocalExecutor
        ports:
        - containerPort: 8080
        command: ["airflow"] 
        args: ["webserver"]
  